/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Landing Theme Tokens (Vibrant Glass & Energy)
        landing: {
          surface: '#faf8ff',
          'surface-dim': '#dad9e0',
          'surface-bright': '#faf8ff',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f4f3fa',
          'surface-container': '#eeedf4',
          'surface-container-high': '#e8e7ee',
          'surface-container-highest': '#e2e2e9',
          'on-surface': '#1a1b20',
          'on-surface-variant': '#434651',
          'inverse-surface': '#2f3036',
          'inverse-on-surface': '#f1f0f7',
          outline: '#747782',
          'outline-variant': '#c4c6d3',
          primary: '#001e52',
          'on-primary': '#ffffff',
          'primary-container': '#00327d',
          'on-primary-container': '#7d9eee',
          secondary: '#b32822',
          'on-secondary': '#ffffff',
          'secondary-container': '#fd5d50',
          'on-secondary-container': '#600004',
          tertiary: '#411100',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#651f00',
          'on-tertiary-container': '#eb845c',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          background: '#faf8ff',
          'on-background': '#1a1b20',
          'vibrant-coral': '#FF5F52',
          'sunny-yellow': '#FFD54F',
          'electric-teal': '#00F5D4',
          'surface-glass': 'rgba(255, 255, 255, 0.75)',
          'glass-border': 'rgba(255, 255, 255, 0.5)',
        },
        // Subpage Theme Tokens (Premium Glass & Geometry)
        subpage: {
          surface: '#f8f9ff',
          'surface-dim': '#cbdbf6',
          'surface-bright': '#f8f9ff',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#eff4ff',
          'surface-container': '#e6eeff',
          'surface-container-high': '#dde9ff',
          'surface-container-highest': '#d3e3ff',
          'on-surface': '#0b1c30',
          'on-surface-variant': '#434653',
          'inverse-surface': '#213146',
          'inverse-on-surface': '#ebf1ff',
          outline: '#737784',
          'outline-variant': '#c3c6d5',
          primary: '#00327d',
          'on-primary': '#ffffff',
          'primary-container': '#0047ab',
          'on-primary-container': '#a5bdff',
          secondary: '#4648d4',
          'on-secondary': '#ffffff',
          'secondary-container': '#6063ee',
          'on-secondary-container': '#fffbff',
          tertiary: '#003a56',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#005277',
          'on-tertiary-container': '#71c6ff',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          background: '#f8f9ff',
          'on-background': '#0b1c30',
          'surface-glass': 'rgba(255, 255, 255, 0.8)',
          'glass-border': 'rgba(255, 255, 255, 0.6)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        heading: ['Sora', 'sans-serif'],
        sora: ['Sora', 'sans-serif'],
      },
      borderRadius: {
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '3rem',
      },
      backgroundImage: {
        'energy-gradient': 'linear-gradient(135deg, #FF5F52 0%, #FFD54F 100%)',
        'tech-gradient': 'linear-gradient(135deg, #00327D 0%, #00F5D4 100%)',
        'primary-gradient': 'linear-gradient(135deg, #0047AB 0%, #6366f1 100%)',
        'accent-gradient': 'linear-gradient(135deg, #6366f1 0%, #0ea5e9 100%)',
      },
      boxShadow: {
        glass: '0 20px 40px rgba(0, 50, 125, 0.06), 0 1px 3px rgba(0, 0, 0, 0.02)',
        'glass-hover': '0 28px 56px rgba(0, 50, 125, 0.12), 0 2px 6px rgba(0, 0, 0, 0.04)',
        coral: '0 12px 24px rgba(255, 95, 82, 0.3)',
        teal: '0 12px 24px rgba(0, 245, 212, 0.25)',
      },
    },
  },
  plugins: [],
};
