const archiver = require('archiver');

/**
 * Builds a WebFont & SVG Sprite bundle for a collection of icons and streams it as a ZIP.
 */
exports.generateWebFontBundle = (collectionName, icons, res) => {
  const archive = archiver('zip', { zlib: { level: 9 } });
  const safeName = collectionName.toLowerCase().replace(/[^a-z0-9]+/g, '-');

  res.attachment(`${safeName}-webfont-bundle.zip`);
  archive.pipe(res);

  // 1. Build SVG Sprite Sheet
  let spriteDefs = '';
  let cssClasses = `/* IconsUniverse Generated WebFont & CSS Sprite: ${collectionName} */\n`;
  cssClasses += `.iu-icon { display: inline-block; width: 1em; height: 1em; stroke-width: 0; stroke: currentColor; fill: currentColor; vertical-align: -0.125em; }\n\n`;

  let demoHtmlIcons = '';

  icons.forEach((icon, index) => {
    const glyphId = `icon-${icon.slug || icon.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
    
    // Extract inner content of svg
    let innerSvg = icon.svgContent || '';
    const match = innerSvg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
    const svgBody = match ? match[1] : innerSvg;

    spriteDefs += `  <symbol id="${glyphId}" viewBox="0 0 24 24">\n    ${svgBody.trim()}\n  </symbol>\n`;

    cssClasses += `.iu-${glyphId} { background-image: url("icons-sprite.svg#${glyphId}"); }\n`;

    demoHtmlIcons += `
      <div class="icon-box">
        <svg class="iu-icon" style="font-size: 36px; color: #00327d;"><use href="#${glyphId}"></use></svg>
        <span class="icon-label">${icon.title}</span>
        <code>&lt;svg class="iu-icon"&gt;&lt;use href="#${glyphId}"&gt;&lt;/use&gt;&lt;/svg&gt;</code>
      </div>`;
  });

  const fullSprite = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
<defs>
${spriteDefs}
</defs>
</svg>`;

  archive.append(fullSprite, { name: 'icons-sprite.svg' });
  archive.append(cssClasses, { name: 'iconsuniverse.css' });

  // 2. Build Interactive HTML Demo Preview
  const demoHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${collectionName} — WebFont & SVG Sprite Demo</title>
  <style>
    body { font-family: 'Segoe UI', system-ui, sans-serif; background: #faf8ff; color: #1a1b20; padding: 40px 20px; }
    h1 { color: #001e52; text-align: center; }
    p { text-align: center; color: #434651; max-width: 600px; margin: 0 auto 40px; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 20px; max-width: 1200px; margin: 0 auto; }
    .icon-box { background: #ffffff; border-radius: 16px; padding: 24px; text-align: center; border: 1px solid rgba(0,0,0,0.06); box-shadow: 0 4px 12px rgba(0,50,125,0.04); transition: transform 0.2s; }
    .icon-box:hover { transform: translateY(-4px); box-shadow: 0 12px 24px rgba(0,50,125,0.08); }
    .icon-label { display: block; margin: 12px 0 8px; font-weight: 600; font-size: 14px; }
    code { display: block; background: #f4f3fa; padding: 6px; font-size: 11px; border-radius: 8px; word-break: break-all; color: #b32822; }
    .iu-icon { display: inline-block; width: 1em; height: 1em; fill: currentColor; }
  </style>
</head>
<body>
  ${fullSprite}
  <h1>${collectionName}</h1>
  <p>Your custom WebFont & SVG Sprite bundle generated by IconsUniverse. Ready for inline web integration.</p>
  <div class="grid">
    ${demoHtmlIcons}
  </div>
</body>
</html>`;

  archive.append(demoHtml, { name: 'demo.html' });
  archive.finalize();
};
